# Error codes for lore

# Pattern validation errors
INVALID_EMPTY_PATTERN = "INVALID_EMPTY_PATTERN"
INVALID_DOUBLE_SLASH = "INVALID_DOUBLE_SLASH"
INVALID_GLOBSTAR_POSITION = "INVALID_GLOBSTAR_POSITION"
INVALID_MULTIPLE_GLOBSTARS = "INVALID_MULTIPLE_GLOBSTARS"
INVALID_MULTIPLE_WILDCARDS_IN_SEGMENT = "INVALID_MULTIPLE_WILDCARDS_IN_SEGMENT"
INVALID_UNSUPPORTED_METACHARACTER = "INVALID_UNSUPPORTED_METACHARACTER"

# Facts file errors
FACTS_FILE_NOT_FOUND = "FACTS_FILE_NOT_FOUND"
FACTS_PARSE_ERROR = "FACTS_PARSE_ERROR"

# Fact structure errors
INVALID_FACT_STRUCTURE = "INVALID_FACT_STRUCTURE"
MISSING_FACT_FIELD = "MISSING_FACT_FIELD"
MISSING_INCL_FIELD = "MISSING_INCL_FIELD"
EMPTY_INCL_LIST = "EMPTY_INCL_LIST"
INVALID_MATCHER_PREFIX = "INVALID_MATCHER_PREFIX"
INVALID_MATCHER_FORMAT = "INVALID_MATCHER_FORMAT"
INVALID_REGEX_PATTERN = "INVALID_REGEX_PATTERN"

INVALID_TAGS_FIELD = "INVALID_TAGS_FIELD"

# CRUD operation errors
DUPLICATE_FACT_ID = "DUPLICATE_FACT_ID"
FACT_NOT_FOUND = "FACT_NOT_FOUND"
